blank_issues_enabled: true
contact_links:
  - name: Support Server
    url: https://melonbot.io/support
    about: For any help needed with LemonCord or any general inquiries, join our support server.
    